### ISSUE TITLE
[Feature Request] Turbo Controller: separate On/Off toggle for Left/Right cross hotbars

### ISSUE THREAD

**Issue by kagoromo** [PunishXIV/PandorasBox#103]
**Is your feature request related to a problem? Please describe.**
There are times when Turbo Controller is not desirable, i.e: Ninja's mudra and Dancer's step inputs.

**Describe the solution you'd like**
I think having separate toggles for Left/Right cross hotbars would solve that problem.
(Or perhaps more generally, a button to temporarily disable Turbo when held, which could be LT/RT)

**Describe alternatives you've considered**
I'm using reWASD for its turbo feature, but it would be nice to have it built into the game so that it will be available for any controller, not just the ones I have set up.

**Additional context**
Simply something similar to this checkbox in the Quick Gather would work great.
![image](https://github.com/PunishXIV/PandorasBox/assets/9592129/fcd6304f-bedd-405e-aed2-6fce83d9a2fc)

**Comment by Taurenkey** [comment]
Not really feasible. Turbo feature is polling hardware signals and not your hotbars.
