### ISSUE TITLE
[Bug Report] Reduce All Items not working

### ISSUE THREAD

**Issue by Jaesaces** [PunishXIV/PandorasBox#125]
**Description:**
The button created by the "Reduce All Items" option under UI only works for the first item.

A search in the Puni.sh discord results in one user who seems to think the issue is tied to frame rate.

**Reproduction:**
1. Turn on "Reduce All Items" from the UI section of Pandora.
2. Gather more than one collectable that can be aetherically reduced.
3. Click "Reduce All" button created by Pandora on the Aetherical Reduction window.

**Expected:**
All items would be reduced one at a time.

**Actual:**
Only one item is reduced.

**Comment by Jaesaces** [comment]
More testing: I tried setting a frame limit of 30 like the other individual, but even that is inconsistent, reducing 1-3 items before it stops working.

**Comment by Taurenkey** [comment]
Probably a YesAlready conflict. It'll be getting turned off going forward.
