### ISSUE TITLE
[Bug Report] Controller Double Tapping

### ISSUE THREAD

**Issue by duckofdeath87** [PunishXIV/PandorasBox#126]
**Describe the bug**
While Pandora is enabled, my PS5 controller double taps. When I disable it, it doesn't double tap

**To Reproduce**
Enable Pandora
Use a controller
Open menus and press the D-Pad
Cursor will move twice 

**Expected behavior**
Pandora shouldn't effect the controller

**Comment by Taurenkey** [comment]
Are you sure you're not using the turbo controller feature?

**Comment by duckofdeath87** [comment]
I swear I checked before and it was disabled, but low and behold it is enabled. My bad
