### ISSUE TITLE
Auto-interact with Objects in Instances issue

### ISSUE THREAD

**Issue by ScarletL1995** [PunishXIV/PandorasBox#127]
For the most part, this feature works great. There is one situation though that this is a problem and that is in special instances like Eureka where there is a teleporter. It keeps trying to click on it to bring up the teleport. You have to disable it or right to get away from the teleporter.

A suggested fix would be to blacklist this specific item or the Eureka Zones. Bonza is one I haven't played in yet but I suspect if they have teleports, it would be the same issue.

But for the most part, this feature has been working great.

**Comment by Taurenkey** [comment]
You're best to adjust your current settings to have a longer cooldown between interactions so you can move away from it.
