### ISSUE TITLE
[Bug Report] Quick Lower Quality Not Working

### ISSUE THREAD

**Issue by EmpyreanKnight** [PunishXIV/PandorasBox#129]
**Describe the bug**

**To Reproduce**
1. Go to Pandora's Box setting page
2. Tick the Quick Lower Quality option from the UI column
3. Lower some HQ items in my inventory
4. Still need to tick the "Lower quality of item" box and click yes

**Expected behavior**
In step 4 from the reproduce procedure, the popup menu and the confirmation operations should be skipped altogether.

**Screenshots**
![image](https://github.com/user-attachments/assets/25dc8d8a-eead-4ff1-bbc3-7ff7b2aa5fe3)

**Additional context**

**Comment by Taurenkey** [comment]
This should already be fixed for the next release. Feel free to reopen it if the next update doesn't fix it.

**Comment by EmpyreanKnight** [comment]
Awesome! Thanks for the lightning fast response!
