### ISSUE TITLE
[Bug Report] Not useing check  Actions even requirments are met

### ISSUE THREAD

**Issue by Shiratama-works** [PunishXIV/PandorasBox#136]
**Describe the bug**
The Twelve's Bounty, The Giving Land, Blessed Harvest II,Nophica's Tidings is not used even checked and meet GP
 requirment (Bountiful Harvest II,Ageless Words works )

**To Reproduce**
Maybe a Japanese client problem?

**Expected behavior**
The Twelve's Bounty, The Giving Land, Blessed Harvest II,Nophica's Tidings should be used when checked and meet GP
 requirment
**Screenshots**
![image](https://github.com/user-attachments/assets/ff6fe6a2-3600-4eab-959b-bce6112f9742)
**Additional context**

**Comment by Taurenkey** [comment]
If I was to guess, you have this enabled.
![image](https://github.com/user-attachments/assets/c13ab205-e572-4a1c-8c53-df1b3561ac84)

You'll need to disable that if you're not intending to gather collectables.

**Comment by Shiratama-works** [comment]
Ah... its intended...it just happens have a collectable..
