### ISSUE TITLE
[Feature Request] Auto-gather in Island Sanctuary when near specified nodes.

### ISSUE THREAD

**Issue by wirchtalksgames** [PunishXIV/PandorasBox#41]
**Is your feature request related to a problem? Please describe.**
Nope, it's more for convenience

**Describe the solution you'd like**
Similar to how Pandora automatically opens chests, I would like it to gather from nodes when they are in range in the island sanctuary. Optionally, you could make it auto gather ALL nodes when you're in range (in the overworld, it would just open the gathering window without having to right click on the node).

**Additional context**
Right clicking on nodes is for chumps; let's make it fully automated. At least it would make island gathering more entertaining and less of a slog.

**Comment by Taurenkey** [comment]
Auto-Interact with Gathering Nodes has an option for Island Sanctuary nodes. It's not specific nodes, but it works on all gathering nodes on the island.

**Comment by wirchtalksgames** [comment]
Apologies, I am dumb.
