### ISSUE TITLE
[Feature Request] Change fixed jumping range in Auto-Lock

### ISSUE THREAD

**Issue by mikka-wookie** [PunishXIV/PandorasBox#82]
**Is your feature request related to a problem? Please describe.**
There is a good spot to farm exp and resources at IS, but main problem is - that character is jumping too often, when using Auto-Lock, and there is very big chance character will be running into the wall.

**Describe the solution you'd like**
Instead of fixed range (8 in your case), add a value that player can enter (in example 10 fixes that issue).

**Describe alternatives you've considered**
Also you can add a checkbox whether player wants to jump or not.

**Additional context**
![image](https://github.com/PunishXIV/PandorasBox/assets/110221071/92ea7a36-c534-4906-8e22-813256f34706)
Something like this.

**Comment by Taurenkey** [comment]
I have been sign-posting people onto using https://github.com/awgil/ffxiv_visland instead. It is more robust for this sort of thing and I will likely remove this feature soon.
