### ISSUE TITLE
[Feature Request] Enable the in-game /autowalk command after gathering

### ISSUE THREAD

**Issue by Nillinn** [PunishXIV/PandorasBox#91]
A setting that enables the in-game command "/autowalk" after finishing gathering a node.
And another one that also enables it after jumping, in the auto-mount features the pluggin already offers.
With a 1 second delay, it should turn on autowalk after a mounted jump without any conflicts.

Example: A checkbox with "enable autowalk" right below the "Jump after mounting" setting:
![image](https://github.com/PunishXIV/PandorasBox/assets/94562218/7526bcf7-7655-44b7-9641-ec982809dbc9)

**Comment by Taurenkey** [comment]
I really need to know the use case for this, because to me this would just lead to people flying into walls.

**Comment by Nillinn** [comment]
Optional feature to increase quality of life by lowering button presses. Same as "Jump after Mounting". Combined, they would allow to walk around gathering all the nearby nodes, by just moving the camera, while still being in control of the character. With a small delay set up in the slider, it would be possible to turn around and prevent flying into a wall.
