### ISSUE TITLE
[Bug Report] Auto stance and Commend randomly stops working in roulettes

### ISSUE THREAD

**Issue by sauronshotdogs** [PunishXIV/PandorasBox#93]
Auto stance and commend sometimes not working in roulettes

Go to random roulette

**Expected behavior**
Upon entering, tank stance activates, upon end, auto commends

There doesn't seem to be any rhyme or reason to it. In some roulettes and dungeons, it's like Pandora's Box will just stop working

**Comment by Nin9sKi** [comment]
I have the same issue
