### ISSUE TITLE
[Feature Request] Mountaineer/Pioneer's Gift in P. Gather

### ISSUE THREAD

**Issue by dontsaydontsay** [PunishXIV/PandorasBox#96]
I think it'd be nice for people leveling gatherers, cause it doubles the exp you get per whack when you successfully hit gatherers boon. Its more CP efficient than Bountiful Harvest by a lot too i think.

**Comment by Taurenkey** [comment]
Pandora gathering is not receiving any further feature updates as it's already scope creeped. It really needs to be pulled out and put into its own plugin.
