### ISSUE TITLE
[Bug Report] Auto-switch gatherers ignores vertical distance

### ISSUE THREAD

**Issue by nonamethanks** [PunishXIV/PandorasBox#98]
If you pass above a mining node at max visible distance and you're a botanist (or vice versa), the job switch happens even if you're very, very far away from the node. 

See the screenshots below. Note the size of the other character on the ground in the first screenshot, and error message in the second. I was at almost max flying height for the map and it still triggered
![image](https://github.com/PunishXIV/PandorasBox/assets/12946050/7ffe6c2a-ff3e-4302-94aa-3269ffd2a182)

![image](https://github.com/PunishXIV/PandorasBox/assets/12946050/e505904d-4693-4d58-a636-fbf60dbbfd28)

**Comment by Taurenkey** [comment]
The feature will respect your height too, and as such I have increased the distance it'll switch from 5y to 10y. Now you should be able to fly over something and as long as you're not really close to it then it won't switch.
